### ISSUE TITLE
HTTP probe failed with statuscode: 500 Back-off restarting failed container

### ISSUE THREAD

**Issue by politrons** [cloudstateio/cloudstate#134]
Hi having this yaml file

https://github.com/politrons/Akka/blob/master/CloudState/src/main/resources/cloudstate.yaml

And this Main and EntityService class

https://github.com/politrons/Akka/tree/master/CloudState/src/main/java/io/cloudstate/shopping

Once that I create a Docker image and I publish in my docker hub, when I deploy using command

`kubectl apply -n cloudstate -f src/main/resources/cloudstate.yaml`

When I see in Kubernetest Dashboard,  my `shopping-cart-deployment ` fail with error

```
Readiness probe failed: HTTP probe failed with statuscode: 500
Back-off restarting failed container
```

Any idea what could be wrong?

Those are the events that I can see in Kubernetes

```
Successfully assigned cloudstate/shopping-cart-deployment-6764bdd9f9-5nc2n to docker-desktop
default-scheduler
-
1
2019-10-28T21:29 UTC
2019-10-28T21:29 UTC
Pulling image "politrons/shopping-cart:latest"
kubelet docker-desktop
spec.containers{user-container}
3
2019-10-28T21:29 UTC
2019-10-28T21:29 UTC
Successfully pulled image "politrons/shopping-cart:latest"
kubelet docker-desktop
spec.containers{user-container}
3
2019-10-28T21:29 UTC
2019-10-28T21:29 UTC
Created container user-container
kubelet docker-desktop
spec.containers{user-container}
2
2019-10-28T21:29 UTC
2019-10-28T21:29 UTC
Started container user-container
kubelet docker-desktop
spec.containers{user-container}
2
2019-10-28T21:29 UTC
2019-10-28T21:29 UTC
Container image "cloudstateio/cloudstate-proxy-native-no-journal:0.4.3" already present on machine
kubelet docker-desktop
spec.containers{akka-sidecar}
1
2019-10-28T21:29 UTC
2019-10-28T21:29 UTC
Created container akka-sidecar
kubelet docker-desktop
spec.containers{akka-sidecar}
1
2019-10-28T21:29 UTC
2019-10-28T21:29 UTC
Started container akka-sidecar
kubelet docker-desktop
spec.containers{akka-sidecar}
1
2019-10-28T21:29 UTC
2019-10-28T21:29 UTC
warning
Readiness probe failed: HTTP probe failed with statuscode: 500
kubelet docker-desktop
spec.containers{akka-sidecar}
149
2019-10-28T21:29 UTC
2019-10-28T21:34 UTC
warning
Back-off restarting failed container
kubelet docker-desktop
spec.containers{user-container}
2
2019-10-28T21:29 UTC
2019-10-28T21:29 UTC

```

Regrds

**Comment by viktorklang** [comment]
Cheked the logs?

**Comment by politrons** [comment]
If you mean the console logs when I run the Kubectl, everything is fine, and said that operators and service were created successful. Sorry I’m new in k8s so if there’s any other logs that I can paste here from the k8s dashboard let me know.

I’m using the yaml version 4.3 could you check in the link that I pasted if everything is fine?

Thanks a lot

**Comment by viktorklang** [comment]
@politrons See the conversation here: https://gitter.im/CloudState-IO/community?at=5db7fd2714d55a3785966c84
