### ISSUE TITLE
Emojis in user documentation do not render properly in the browser

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/cloudstate#178]
**_What did you see?_**

https://cloudstate.io/docs/user/lang/index.html#3rd-party-libraries
<img width="519" alt="Screenshot 2020-01-10 at 11 42 38" src="https://user-images.githubusercontent.com/12616445/72147211-4f822500-339e-11ea-8088-172eb805f1df.png">

**_What did you expect to see?_**
more emojions

**_Additional Information_**
#170 might have introduced that.

**Comment by michaelpnash** [comment]
The link "source code for this page here" *does* show all the icons, it seems, interestingly.

**Comment by marcellanz** [comment]
@michaelpnash It may be the markdown parser not capable of, but I'm not an "emoji" expert :-)

**Comment by sleipnir** [comment]
I suggest removing the emojis since they were inherited from another repository and may not make sense here.
We can simply write (supported, not supported, partially supported, unstable, etc ...)

**Comment by sleipnir** [comment]
@ChristopherAndre what do you think?

**Comment by ChristopherAndre** [comment]
@sleipnir : You're right, let's use single letters instead! What about **"S"** for "Supported", **"N"** for "Not Supported", **"P"** for "Partial support" and **"?"** for "Support status unknown" ?

**Comment by viktorklang** [comment]
I'd rather have it in text instead of a letter, that will translate easier using Google Translate etc.

**Comment by ChristopherAndre** [comment]
@viktorklang There would still be a legend of what these letters mean.

**Comment by ChristopherAndre** [comment]
I have created a PR to address that: basically, I converted the emoji reference to their unicode representation. Hopefully, that should solve the problem!
Let me know if you prefer to have full text instead!

**Comment by sleipnir** [comment]
> I have created a PR to address that: basically, I converted the emoji reference to their unicode representation. Hopefully, that should solve the problem!
> Let me know if you prefer to have full text instead!

Cool!

**Comment by ChristopherAndre** [comment]
PR has been merged.
@marcellanz please test on your browser(s) and let us know if it works for you!

**Comment by jroper** [comment]
Thanks @ChristopherAndre, yes, the colon - emoji name - colon syntax is not markdown, so there's no reason to expect it to work, it works in GitHub because GitHub uses their own flavour of markdown called GitHub Flavoured Markdown where they've added emoji support.

The only comment I have is on accessibility - a screen reader will usually read the name of the emoji, so for example, the question marks name in unicode is "Black Question Mark Ornament", that's what someone using a screen reader is going to hear. GHFM is a little better, because they don't use unicode emojis, instead they use an image with an alt text of their name for the emoji, which is "question". Still not ideal. The best solution would be to not use emojis at all, but instead use images with a sensible alt text, ie, we can set the alt text for the question mark to "Unknown", and for the cross to "Not supported".

**Comment by marcellanz** [comment]
@ChristopherAndre I checked with my iPad and its visually overwelming. Personally I'm not that of a fan of emojis, or the exessive use of them.

After thinking a bit about it, I've got an impression of, that the page overloads my perception visually.

As an example on this page there are two warnings, one with a explanation mark, the other with a pointing finger. On the same time there is a markown "warning" element to visualize a warning note (used on other locations in the documentation).

So the page shows me a lot of warnings where it perhaps could solely show levels of support for certain  features of the language support libraries. But at the same time, this page specifically should welcome users of languages to be used.

What do others think⁉️perhaps I'm just a bit too emoji-onal about this 😃😅

**Comment by ChristopherAndre** [comment]
I like @jroper 's suggestion to use images but:
- I am not sure how to incorporate images in Paradocs
- what images to use that would not overwhelm @marcellanz ?

**Comment by marcellanz** [comment]
@ChristopherAndre "overwhelm" is subjective for sure. "visually loaded" might be a better term. perhaps I should provide an alternative.

**Comment by ChristopherAndre** [comment]
@marcellanz I was only using "overwhelm" as you used it in your previous message (English is not my first language either). The question still remains: what do you think would better? I think having colors would make it faster to parse than text but I'm open to any suggestion.
Also, would someone know how to incorporate images in Paradox (their website is currently down so I can't browse the doc)?

**Comment by marcellanz** [comment]
Issue is fixed. Other issue if relevant should be better handled by a documentation styleguide driven new issue.
