### ISSUE TITLE
Graal support in the backend-platform

### ISSUE THREAD

**Issue by viktorklang** [cloudstateio/cloudstate#18]
It would be extremely interesting to be able to make the sidecar application a Graal Native Image.

**Comment by viktorklang** [comment]
Useful links:

https://github.com/vmencik/akka-graal-native/blob/master/README.md
https://www.graalvm.org/docs/getting-started/
https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md

One possible solution is to have the AKKA backend Reference Implementation launched in a Graal Docker Image with the Assisted Configuration agentlib enabled, then running a simulation to exercise all the code paths needed to generate a configuration, which can then be fed into the native image builder to generate a native image of the RI.

**Comment by raboof** [comment]
:+1: . Also see https://github.com/vmencik/akka-graal-config

**Comment by viktorklang** [comment]
Currently hit https://github.com/oracle/graal/issues/1306

**Comment by viktorklang** [comment]
See: https://github.com/oracle/graal/issues/1376
See: https://github.com/oracle/graal/issues/955

**Comment by viktorklang** [comment]
This is also worth keeping an eye on, as it is currently cumbersome to deal with sunec.dylib: https://github.com/oracle/graal/issues/1336

**Comment by viktorklang** [comment]
Implemented in master
