### ISSUE TITLE
Link User Language Supports in the README.md

### ISSUE THREAD

**Issue by viktorklang** [cloudstateio/cloudstate#185]
Here: https://github.com/cloudstateio/cloudstate#client-api

**Comment by sleipnir** [comment]
What do you think of just adding something like:

See: link_to_readme_of_specific_repository

For example:
```
Client API

TODO: introduction to client APIs, discuss gRPC protocol, polyglot, common features, etc.

JavaScript API
See link_to_javascript_docs

Java API
See link_to_java_docs

Kotlin API
See https://github.com/cloudstateio/kotlin-support

TODO: add general docs
```

**Comment by viktorklang** [comment]
@sleipnir Hmmm, what do you think about the pros and cons of that?

**Comment by sleipnir** [comment]
@viktorklang follow:

Pros:
* Documenting libraries with their use cases, peculiarities and idiosyncrasies tends to be an extensive and complex process. Being separate from the main doc you allow them to evolve independently.
* Allows the user to browse different pages and only those that are of current interest.
* Reduces the visual pollution of the Readme

Cons:
* Tends to decrease the cohesion of language and style

To mitigate the cons include a brief description of the general concepts before refer to the linking to a page, this must resolve

**Comment by viktorklang** [comment]
The challenge is to include code from other repositories / enure cohesion over time.

**Comment by sleipnir** [comment]
> The challenge is to include code from other repositories / enure cohesion over time.

Life is not easy :)
Lol

Well, I don't know what to say. Just wanted to leave some ideas on the topic

**Comment by marcellanz** [comment]
> The challenge is to include code from other repositories / enure cohesion over time.

@sleipnir @viktorklang I'd like to have that validated at least for the user support libs that cloudstate provides through the project. Having a TCK implemented and ran against a user language support library release should be enough. If it's not, the TCK might not be complete.

**Comment by sleipnir** [comment]
> > The challenge is to include code from other repositories / enure cohesion over time.
> 
> @sleipnir @viktorklang I'd like to have that validated at least for the user support libs that cloudstate provides through the project. Having a TCK implemented and ran against a user language support library release should be enough. If it's not, the TCK might not be complete.

LGTM @marcellanz

**Comment by rstento** [comment]
@pvlugter & @viktorklang, it appears to me that this (linking to Javadocs and JavaScript api doc) has been done in both the Cloudstate and AS doc, not sure about the README, but at the time this issue was written, the README was the doc. Do you think we can close this?

**Comment by pvlugter** [comment]
Yes, I think this can be closed. Language support docs are released independently, but available together, so the original issue on linking in the README is no longer relevant.
