### ISSUE TITLE
Expose Configuration API in Cloudstate class

### ISSUE THREAD

**Issue by sleipnir** [cloudstateio/cloudstate#191]
It would be interesting if we could start a Cloudstate instance with a configuration object (like CloudstateRunner.Configuration). Thus, we could programmatically configure the environment without depending on environment variables. It would also be interesting from the point of view of implementations based on java support, like kotlin support for example.

Example:
```
public final class Main {
  public static final void main(String[] args) throws Exception {
   Configuration conf = .....

    new CloudState(conf)
        .registerEventSourcedEntity(
            ShoppingCartEntity.class,
            Shoppingcart.getDescriptor().findServiceByName("ShoppingCart"),
            com.example.shoppingcart.persistence.Domain.getDescriptor())
        .start()
        .toCompletableFuture()
        .get();
  }
}
```

Or:
```
public final class Main {
  public static final void main(String[] args) throws Exception {
   Configuration conf = .....

    new CloudState()
        .withConfiguration(conf)
        .registerEventSourcedEntity(
            ShoppingCartEntity.class,
            Shoppingcart.getDescriptor().findServiceByName("ShoppingCart"),
            com.example.shoppingcart.persistence.Domain.getDescriptor())
        .start()
        .toCompletableFuture()
        .get();
  }
}
```

**Comment by sleipnir** [comment]
I didn't notice it but this is already possible in the overloaded start method

**Comment by sleipnir** [comment]
But this api is not available in the maven version 0.4.3. Could you publish the new version with this feature?

**Comment by sleipnir** [comment]
ping @pvlugter

**Comment by pvlugter** [comment]
I've published the current cloudstate-java-support from master as 0.5.0. We're still to figure out the release cycles and versioning for the support libraries that are in the main repository, so we'll get something sorted out, and with regular snapshots from master to depend on as well.

**Comment by pvlugter** [comment]
Sorry, that latest version depends on a snapshot of akka-gprc. So the https://dl.bintray.com/akka/maven repo will also be needed.

**Comment by pvlugter** [comment]
Have published some more versions of java-support. Try `0.4.7`.

**Comment by sleipnir** [comment]
Thanks @pvlugter
