### ISSUE TITLE
new kotlin doc – visual and cosmetic glitches

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/cloudstate#209]
@sleipnir the Kotlin Documentation is great work :)

I've read through it again as it's now on the [cloudstate.io](https://cloudstate.io/docs/user/lang/kotlin/index.html) website and I've seen some minor cosmetic/visual issues that I list below and did not have time to fix directly. I let them screenshot'ed below.

---
1)
**location**: https://cloudstate.io/docs/user/lang/kotlin/gettingstarted.html
**what**: this might be a link to the Docker project? the URL is missing.

<img width="436" alt="Screenshot 2020-03-14 at 18 44 40" src="https://user-images.githubusercontent.com/12616445/76687402-df08b600-6623-11ea-9c86-c0e6afb14d67.png">

---
2)
**location**: https://cloudstate.io/docs/user/lang/kotlin/gettingstarted.html
**what:** visual glitch

<img width="295" alt="Screenshot 2020-03-14 at 18 42 03" src="https://user-images.githubusercontent.com/12616445/76687368-80433c80-6623-11ea-9bb9-f29d19a71d63.png">

---
3)
**location**: https://cloudstate.io/docs/user/lang/kotlin/gettingstarted.html
**what:** visual glitch

<img width="588" alt="Screenshot 2020-03-14 at 18 44 01" src="https://user-images.githubusercontent.com/12616445/76687392-c7313200-6623-11ea-9645-244241fbc7e3.png">

---
4)
**location**: https://cloudstate.io/docs/user/lang/kotlin/eventsourced.html
**what:** visual glitch

a)
<img width="506" alt="Screenshot 2020-03-14 at 18 47 45" src="https://user-images.githubusercontent.com/12616445/76687453-4d4d7880-6624-11ea-82c3-9faab936b586.png">

b)
<img width="486" alt="Screenshot 2020-03-14 at 18 50 05" src="https://user-images.githubusercontent.com/12616445/76687483-a0273000-6624-11ea-8e43-6dc33f36713f.png">

c)
<img width="523" alt="Screenshot 2020-03-14 at 18 52 58" src="https://user-images.githubusercontent.com/12616445/76687512-07dd7b00-6625-11ea-9846-51dfb7a5ea5b.png">

d)
<img width="616" alt="Screenshot 2020-03-14 at 18 55 13" src="https://user-images.githubusercontent.com/12616445/76687559-5a1e9c00-6625-11ea-8960-43afca8bded5.png">

---
5)
**location**: https://cloudstate.io/docs/user/lang/kotlin/serialization.html
**what:** the link to serialization information does not work:
https://cloudstate.io/docs/src/main/paradox/user/lang/java/serialization.md

---
6)
**location**: https://cloudstate.io/docs/user/lang/kotlin/gettingstarted.html
**what:** here 'CloudState' in camel case is mentioned what does that reference to? I have not found a type/class in the source to be named like it. As it's `displayed in code style' one could assume a type, if not and referenced Cloudstate, it should be non code or ne properly named. It might even mention this high order function you mentioned here: https://github.com/cloudstateio/cloudstate/pull/201#discussion_r388327302

<img width="535" alt="Screenshot 2020-03-15 at 05 20 22" src="https://user-images.githubusercontent.com/12616445/76695203-aea13600-667c-11ea-842a-93c6afe2ccef.png">

**Comment by sleipnir** [comment]
Hi @marcellanz , thanks for the insights, but some of the things you can do relate to me not.
For example, I did not understand what the problem is 6. Did not find the CloudState of action and did not understand the problem of the function it refers to. Kotlin supports has a cloud function that must be used at the entry point of the application, usually its main function, to boot or cloud server. In this case everything is in the lower case.
In problem 1 I also did not understand what url refers to.

I promise to take a look around the week and try to find the points you mentioned.
Thanks

**Comment by sleipnir** [comment]
On the bold, it seems that Paradox gets a little lost in some cases. Works perfectly in my Markdown editor

**Comment by sleipnir** [comment]
@marcellanz  can you take a look at this PR?
https://github.com/cloudstateio/cloudstate/pull/210

**Comment by marcellanz** [comment]
> @marcellanz can you take a look at this PR?
> #210

@sleipnir Thanks, I will. How does it look like in paradox?

**Comment by sleipnir** [comment]
> > @marcellanz can you take a look at this PR?
> > #210
> 
> @sleipnir Thanks, I will. How does it look like in paradox?

Hi @marcellanz  I'm getting the error "[error] npm ERR! Failed at the cloudstate@0.0.3 jsdoc script." when trying to run the paradox, so I'm trusting the good old Markdown

**Comment by marcellanz** [comment]
@sleipnir ran it here...

- For 1, The Docker link seems to be the same (missing) with all other lang support docs (except the [Go](https://cloudstate.io/docs/user/lang/go/gettingstarted.html) one 😇)
- ran it in paradox, AFAICS all is well, except for 6. See my comment in the PR.

<img width="512" alt="Screenshot 2020-03-17 at 04 19 03" src="https://user-images.githubusercontent.com/12616445/76818743-a412a800-6806-11ea-82ae-ae220e122f5b.png">

**Comment by sleipnir** [comment]
@marcellanz Please see the new commits in PR.

**Comment by marcellanz** [comment]
@sleipnir looks good from my side, thank you.

**Comment by marcellanz** [comment]
fixed with #210
