### ISSUE TITLE
oss-banner: misspelling link to cloudstate by lightbend site 

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/cloudstate#222]
https://github.com/cloudstateio/cloudstate/blob/a362dacf93d856fa60a07a23bce237beeca6d010/docs/src/main/paradox/_template/oss-banner.st#L41

was:
https://www.lightbend.com/cloustate-by-lightbend
should be:
https://www.lightbend.com/cloudstate-by-lightbend

**Comment by marcellanz** [comment]
@jroper ping

**Comment by sleipnir** [comment]
Which include Kotlin in the list on the official Lightbend page: D

![include-kotlin](https://user-images.githubusercontent.com/342502/78034749-841ed080-733e-11ea-853d-8e9f5551be53.png)

**Comment by rasummer** [comment]
FIx has been submitted

**Comment by marcellanz** [comment]
@rasummer did send a PR along the issue and @viktorklang merged https://github.com/cloudstateio/cloudstate/commit/2d8eae661938343f1a5e290538909690e88cc455

**Comment by marcellanz** [comment]
@sleipnir perhaps open a new PR for that?

**Comment by sleipnir** [comment]
> @sleipnir perhaps open a new PR for that?

@marcellanz I think it is unnecessary since it is the company's corporate page and has no relation to the community repository. The comment remains only.
Sorry if the comment was out of context for your PR.

**Comment by marcellanz** [comment]
> > @sleipnir perhaps open a new PR for that?
> 
> @marcellanz I think it is unnecessary since it is the company's corporate page and has no relation to the community repository. The comment remains only.
> Sorry if the comment was out of context for your PR.

@sleipnir np. let @viktorklang know?
