### ISSUE TITLE
Add Dart support.

### ISSUE THREAD

**Issue by hepin1989** [cloudstateio/cloudstate#230]
refs:https://github.com/grpc/grpc-dart

**Comment by sleipnir** [comment]
https://github.com/sleipnir/cloudstate-dart-support

**Comment by sleipnir** [comment]
Repository now is https://github.com/cloudstateio/dart-support

**Comment by sleipnir** [comment]
I think we can close this issue and if there is a pending issue with Dart language support issues are opened in the Dart support repository https://github.com/cloudstateio/dart-support

**Comment by sleipnir** [comment]
ping @pvlugter @hepin1989

**Comment by pvlugter** [comment]
Sounds good to close here 👍
