### ISSUE TITLE
Network Partition Handling

### ISSUE THREAD

**Issue by michaelpnash** [cloudstateio/cloudstate#236]
As a user of Cloudstate, I would like the platform to "handle" network partitions for me, ensuring that I don't have data corruption or lowered availability as much as practical, so that I don't have to build this into my applications myself.

"Handle" in this context probably means detect, take action, and (if possible) alert (or log, so I may have my infrastructure alert if I wish)

**Comment by sleipnir** [comment]
What types of network partitions would you like the protocol to address? Between the sidecar and the entity function? Or between the Akka cluster?

I noticed in some tests that after the proxy connects to an entity and a discovery message exchange is successful, the proxy never tries to communicate with the entity again until there is an external request. 
Perhaps the proxy should perform a heartbeat message from time to time, or what I think is best, monitor the Liveness Probe of the entity application and thereby feed some kind of metric.
I believe that the proxy can implement some treatment policy via RestartFlow in the event that a request for a user function fails. But I'm not sure about that, maybe @jroper or @viktorklang sis the best persons to answer that.

**Comment by michaelpnash** [comment]
I was thinking only of Akka Cluster partitioning, but you make a good point, that's not the only failure point we could see.

**Comment by hseeberger** [comment]
All containers (entity, proxy, etc.) in a Pod are co-located and share the same network address, hence they are not affected by network partitions.

Failures like described might occur and the suggested treatment might be a good solution, but should be out of scope of this issue. @sleipnir, could you open a new issue please, if that makes sense?

**Comment by sleipnir** [comment]
@hseeberger I opened a new issue as suggested

**Comment by sleipnir** [comment]
but I think what he meant was about the possible network failures in the formation of the AKKA Cluster and not about the connections that occur over the same namespace. That's why I asked the previous question to disambiguate the question.

Am I right @michaelpnash ?

**Comment by edwardcallahan** [comment]
The split brain resolver automatically handles network partitions. The [Lease](https://doc.akka.io/docs/akka-enhancements/current/split-brain-resolver.html#lease) strategy may be a good choice as we already have the k8s requirement and require a dynamic solution.

**Comment by viktorklang** [comment]
@edwardcallahan How many clusters & nodes will it be able to support?

**Comment by edwardcallahan** [comment]
Majority is the better, more conservative approach. 
Enable for Majority.
