### ISSUE TITLE
Incremental compilation for hocon2json

### ISSUE THREAD

**Issue by jroper** [cloudstateio/cloudstate#281]
The way the build is structured at the moment, we create multiple Docker images from the proxy core project. These docker images are identical, except for the arguments passed in the call declaration. However, currently, because hocon2json re does its thing on every execution, the timestamps of the files it outputs get updated, and when they then get packaged into a jar file, this results in a changed jar file, which then means Docker considers the context change, and so has to rerun the native image build even when there are no meaningful changes, such as during a release where we build each image in succession.

If hocon2json only updated the files when they changed, this would avoid that.

**Comment by viktorklang** [comment]
Pinging @dwijnand
