### ISSUE TITLE
eventing.proto is missing from cloudstate-java-support.jar

### ISSUE THREAD

**Issue by vkorenev** [cloudstateio/cloudstate#285]
`java-shopping-cart` sample fails to compile because protoc cannot find `cloudstate/eventing.proto`. As a workaround, this file can be copied to the directory containing project proto sources, e.g. `src/main/proto`. See lightbend/cloudstate-samples#248

**Comment by viktorklang** [comment]
@vkorenev You can always pull it from here as a part of the build: "https://raw.githubusercontent.com/cloudstateio/cloudstate/master/protocols/frontend/cloudstate/eventing.proto"

**Comment by vkorenev** [comment]
@viktorklang yes, I copied it from there. However, it would be nice to have all the proto files which users might want to import distributed inside a jar.

**Comment by viktorklang** [comment]
@vkorenev Agreed. @pvlugter wdyt—should we add an automatic copy of the needed protos into the java-support jar as a part of the build?

**Comment by sleipnir** [comment]
@viktorklang @pvlugter I think the proto files can be in a separate artifact and imported in java support as a dependency

**Comment by viktorklang** [comment]
@sleipnir That makes sense as well. Perhaps follow the tradition of having
a "protobuf" qualifier on the artifact?

**Comment by sleipnir** [comment]
yes i believe so

**Comment by pvlugter** [comment]
Looks like the proto files are published in cloudstate-java-support already, but eventing was added after the version being used (0.4.3). We're still to figure out the release cycles for support libraries that are in the main repository, so it's not clear on version alignment and releases are ad hoc.

I've published the latest version of java-support for cloudstate master as `0.5.0`. Note, didn't realise we were on a snapshot of akka-gprc, so the `https://dl.bintray.com/akka/maven` repo is also required for this version. I can also go back to an earlier commit and publish a `0.4.4` — currently not clear which commit will be compatible with what though. We're going to need protocol versioning and negotiation between the cloudstate proxy and language support modules.

**Comment by pvlugter** [comment]
Okay, I've gone back to a few points where java-support has changed and retro-assigned these versions and published releases, as I'm not sure what is compatible or needed. Some of these depend on a snapshot for akka-http (which is the `https://dl.bintray.com/akka/snapshots` repo). Versions are git tagged, as `java-support-0.4.x`.

The last one, `0.4.7`, should have everything and doesn't have snapshot dependencies. @vkorenev, let us know how that works in the sample.

I'll also keep this issue, for if we want to move the proto files into a separate jar.

**Comment by sleipnir** [comment]
i was trying to maintain the support languages i agreed with a current version of the protocol in the 0.5.x series i don't know if you were using or downgraded those versions to maintain compatibility. What do you think? It would be better to make or downgrade to the 0.4.x series also for the support languages

**Comment by vkorenev** [comment]
@sleipnir I think we can upgrade `cloudstate-java-support` in `kotlin-support` to 0.5.0. It depends on 0.8.x version of akka-grpc, which we are already using for integration tests because it does not have problems with gradle.

**Comment by sleipnir** [comment]
Kotlin update to 0.5.x status in https://github.com/cloudstateio/kotlin-support/pull/33

**Comment by vkorenev** [comment]
Fixed in 0.4.7.
