### ISSUE TITLE
Update entity passivation

### ISSUE THREAD

**Issue by pvlugter** [cloudstateio/cloudstate#298]
Akka 2.6 has entity passivation built-in now. See `akka.cluster.sharding.passivate-idle-entity-after` setting and [discussion](https://github.com/cloudstateio/cloudstate/pull/293/files#r419180864).

Or we may want to allow passivation timeouts to be configurable per entity type on the user side?

**Comment by ralphlaude** [comment]
I think it would be better to have passivation timeouts configurable per entity type. Making the passivation timeouts is for flexible for the users and it can adapted depending on the use cases. I would go for those properties in the conf file:
```
value-entity {
  passivation-timeout = 30s
}
eventsourced-entity {
 passivation-timeout = 30s
}
replicated-entity {
  passivation-timeout = 30s
}
```
@pvlugter what do you think?

**Comment by marcellanz** [comment]
>Or we may want to allow passivation timeouts to be configurable per entity type on the user side?

Would it be feasible, or even possible with the proxy, to configure that per registered entity and therefore via discovery?

**Comment by pvlugter** [comment]
Yes, having passivation timeouts configured in the language supports and part of entity discovery makes sense to me.

And having per state model defaults in the proxy sounds good too.

**Comment by ralphlaude** [comment]
> > Or we may want to allow passivation timeouts to be configurable per entity type on the user side?
> 
> Would it be feasible, or even possible with the proxy, to configure that per registered entity and therefore via discovery?

It could be possible to do via the entity discovery but it need a bit of tweaking for the discovery process and also for the service classes (e.g `io.cloudstate.javasupport.Service` in the java support) to convey this information. Now the`XXXSupportFactory`classes are instantiated before the discovery process and this could be slightly changed, not sure if it will work. The option of having per registered sounds very good and is more flexible. 

Having it in the proxy in the conf file sounds easier for now.

**Comment by pvlugter** [comment]
This was auto-closed in #484. I'm reopening for following up with passivation timeouts configured in language supports via the discovery protocol.

**Comment by ralphlaude** [comment]
I will take a look on this again.

**Comment by pvlugter** [comment]
Also this older issue on configurable entity passivation: #111
