### ISSUE TITLE
Use Java 11 for GraalVM native-image

### ISSUE THREAD

**Issue by hseeberger** [cloudstateio/cloudstate#301]
Currently we are using the tag `20.0.0` for the native-image Docker image in our `build.sbt`. This refers to Java 8!

In order to use Java 11 we have to change to `20.0.0-java11`:

``` scala
val GraalVersion = "20.0.0-java11"
```

**Comment by viktorklang** [comment]
@hseeberger Can't change GraalVersion to "20.0.0-jav11" since we have deps which use it. So I'll fix this in another way.
