### ISSUE TITLE
GraalVM CircleCI nigtly builds

### ISSUE THREAD

**Issue by srikanthops** [cloudstateio/cloudstate#308]
Limit CircleCI builds for nightly, only when there is a code change.

**Comment by pvlugter** [comment]
It looks like the CircleCI builds are already triggered by pushed changes, so not sure what is being suggested here.

**Comment by srikanthops** [comment]
Closing this PR.. 
In the past, we used to do GraalVM build which used to take about an hour..
At present we are only doing tck test with native-image and it takes about 14 minutes
