### ISSUE TITLE
WIP: Proposal spring-boot-cloudstate-starter repository added to cloudstateio

### ISSUE THREAD

**Issue by sleipnir** [cloudstateio/cloudstate#330]
https://github.com/sleipnir/spring-boot-cloudstate-starter/issues/7

**Comment by sleipnir** [comment]
Hi @viktorklang and @pvlugter 
Now that the PR https://github.com/cloudstateio/cloudstate/pull/282 has been approved, could we officially include the springboot repository in the project?

**Comment by pvlugter** [comment]
Sounds good to move to cloudstateio now. @sleipnir, just transfer the repo when ready. I can add the extra teams and permissions and so on.

**Comment by sleipnir** [comment]
Thanks @pvlugter I requested the transfer. You might want to rename the repository to springboot-support or something.
I think it's cool to have a team but besides me I don't know who would be a member

**Comment by pvlugter** [comment]
Yes, let's still create a team. I don't see the transfer though...

**Comment by sleipnir** [comment]
I had typed cloudstate instead of cloudstateio....
Now it was @pvlugter

**Comment by pvlugter** [comment]
Oh, makes sense. Renamed to `springboot-support` now
