### ISSUE TITLE
[Node support] Support async command handlers

### ISSUE THREAD

**Issue by vkorenev** [cloudstateio/cloudstate#332]
Please consider adding support for functions that return `Promise` as command handlers. A lot of Javascript libraries return values asynchronously via promises or callbacks, which can be converted to promises. Using such API in command handlers is not easy at the moment.

**Comment by vkorenev** [comment]
Failed promises should be handled properly (related to #333).

**Comment by pvlugter** [comment]
Command handlers returning promises (with `then` methods) added in #367

https://github.com/cloudstateio/cloudstate/blob/c7651e97cd60bf14b4afc1f7fe6d6f0dcee0b3f1/node-support/src/action-support.js#L107
