### ISSUE TITLE
[Java support] Exception in command handler results in malformed gRPC response

### ISSUE THREAD

**Issue by vkorenev** [cloudstateio/cloudstate#344]
If an exception is thrown in a command handler of a user function written in Java (including `FailInvoked` thrown by `CommandContext.fail()`, the caller (gRPC client) does not receive a gRPC error. Instead the gRPC response seems to be truncated.

Output from `grpcurl` client:
```
Error invoking method "com.example.inventory.ProductInventory/ReserveProduct": grpc call for "com.example.inventory.ProductInventory.ReserveProduct" failed: EOF
```

**Comment by viktorklang** [comment]
@jroper @pvlugter Any thoughts here?

**Comment by jroper** [comment]
I guess it's just a bug.

**Comment by pvlugter** [comment]
Discussed at the last contributor's call. May be a regression from changes at some point. Would be useful to have it covered by tests...
