### ISSUE TITLE
Provide an option for a gRPC route for customers

### ISSUE THREAD

**Issue by justinhj** [cloudstateio/cloudstate#350]
Several potential use cases have come up during my participation of the alpha test that suggest that giving customers access via gRPC to their lbcs services would be beneficial. Please forgive me if this is already currently possible, but I believe right now you can access the routes to user services only via HTTP or grpc-web.

Their are two use cases I came up with...

1) User builds this own frontend or other service that must interact with their Cloudstate service and can use gRPC directly to avoid the overhead of grpc (while of course losing some benefits of gRPC on the frontend side). Services that feed commands to a user function via a kafka topic or some other feed also don't need to use http or grpc. 
2) Load testing. For load testing it's better to be able to reach the service directly rather than also have to measure the effects of the grpc-web proxy.

Ideally direct support for gRPC would be able to configured using the routes.yaml

**Comment by sleipnir** [comment]
I don't know if I understand the use case. But today the sidecar proxy can serve any data stream via gRPC, gRPC-web, HTTP, Google PubSub. Support for Kafka should come in the near future but the type of serialization used should remain Protobuf as this is what allows the proxy to communicate with user functions written in any language that supports the gRPC protocol. gRPC-web is just another protocol that the sidecar proxy supports.
If the question is related to exposing gRPC endpoints outside a Kubernetes Cluster, I think you will find some information in the Istio documentation, or Kubernetes itself.
As you mention LBCS maybe someone from the Lightbend team can give you some tips on how to set this up in the Lightbend Cluster

**Comment by justinhj** [comment]
Thanks for the reply, yeah this issue is not related to the open source project. Closing.
