### ISSUE TITLE
TCK – verify entity passivation

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/cloudstate#359]
An [issue](https://github.com/cloudstateio/go-support/issues/27) reported in v0.1.0 of the Go Support brought up a testcase the TCK could verify for state models. 

The proxy sets the timeout for entity passivation to 30s for now. The property [`cloudstate.proxy.passivation-timeout`](https://github.com/cloudstateio/cloudstate/blob/v0.5.1/proxy/core/src/main/resources/reference.conf#L17) can be set to a different value for the TCK running the proxy.

**Tasks**
- [x] verify entity passivation for eventsourcing with the TCK
- [x] verify entity passivation for CRDTs. I will include this for CRDTs with the new CRDT TCK [this issue](https://github.com/cloudstateio/go-support/issues/24) to be solved.

[Go issue#27](https://github.com/cloudstateio/go-support/issues/27#issuecomment-643663849) demonstrates how it can be verified.

**Comment by marcellanz** [comment]
On passivation this message is logged by the proxy:
```
2020-06-14 23:42:13.486 INFO akka.actor.LocalActorRef - Message [akka.actor.Status$Failure] to Actor[akka://cloudstate-proxy/system/sharding/ShoppingCart/50/mrcl#-1089585546] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://cloudstate-proxy/system/sharding/ShoppingCart/50/mrcl#-1089585546] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

What does it mean by the proxies perspective?

**Comment by pvlugter** [comment]
Yes, I've also noticed the deadletter on passivation and have been meaning to look at it.

**Comment by viktorklang** [comment]
Good, thanks @pvlugter!

Thanks for opening this issue, @marcellanz

**Comment by pvlugter** [comment]
I've moved the dead letter log to issue #389

**Comment by pvlugter** [comment]
Entity passivation in the language supports is now verified through the new TCK tests which call the subprotocols directly. We can also test the passivation timeouts from the language supports when based on #486. I'll close this issue as resolved.
