### ISSUE TITLE
Convert doc source from markdown to asciidoc

### ISSUE THREAD

**Issue by rstento** [cloudstateio/cloudstate#371]
To provide a better user experience and give authors the flexibility to add more sophisticated formatting for tables and lists, convert the documentation to asciidoc.

**Comment by marcellanz** [comment]
@rstento @pvlugter I tried to build https://github.com/cloudstateio/cloudstate/pull/368 and all went well using Antora the first time and building and viewing it.

With the next milestone for the Go support, I have planned to re-write [its documentation](https://github.com/cloudstateio/go-support/tree/master/docs) by larger parts. What do you think, should I start doing this already with Antora and therefore asciidoc or should I stick with paradox?

**Comment by rstento** [comment]
Hi @marcellanz, asciidoc please. https://docs.antora.org/antora/2.3/organize-content-files/ describes the organization of the doc tree if you are not familiar with Antora. Thanks!

**Comment by marcellanz** [comment]
At the contributors call today (2020-06-30) we discussed shortly how I should go forward with Antora or Paradox for the Go Support to be documented. As not everything is clear right now, as I understood, I'll go forward with Paradox and when ready, port it to Antora.

**Comment by coreyauger** [comment]
PR to make sure that everyone has `jsdoc` and that the required node dependancies are installed: https://github.com/cloudstateio/cloudstate/pull/421

**Comment by pvlugter** [comment]
All the docs are converted now: https://cloudstate.io/docs/
