### ISSUE TITLE
cloudstate-0.5.1.yaml asset missing from 0.5.1 release

### ISSUE THREAD

**Issue by jtownley** [cloudstateio/cloudstate#373]
`cloudstate-0.5.1.yaml` asset missing from 0.5.1 release https://github.com/cloudstateio/cloudstate/releases/tag/v0.5.1

![Screen Shot 2020-06-26 at 8 46 34 AM](https://user-images.githubusercontent.com/250238/85870108-e0508f80-b789-11ea-8fea-5b70a0ab002a.png)

Thus breaking the documentation here:
https://cloudstate.io/docs/core/current/user/deployment/installing.html

**Comment by pvlugter** [comment]
Thanks @jtownley. Looks like this was [added to the automated release](https://github.com/cloudstateio/cloudstate/commit/a4bc2ac) and then [removed again](https://github.com/cloudstateio/cloudstate/commit/4a3e47e). Not sure what the expected approach should be. @jroper?

**Comment by jroper** [comment]
I don't know if I answered this in another forum, I thought I had answered it... but I never managed to get the automatic publishing of the YAML working, and it wasn't high enough priority at the time for me to look further into it.

**Comment by pvlugter** [comment]
I've uploaded the yaml file for 0.5.1, with a script that I'll add to the travis build.
