### ISSUE TITLE
Add in kubernetes test to native image build

### ISSUE THREAD

**Issue by jroper** [cloudstateio/cloudstate#379]
Right now, we only test the native image build against the TCK, we don't test actually running it in Kubernetes. This means a bunch of things don't get exercised:

* Kubernetes cluster bootstrap
* Remoting
* Serialization of remotely sent messages

I'm 110% positive that the current native image build therefore won't work in Kubernetes.

We already have the minikube smoke tests, we should use that, but we should do a little more than what they currently do:

* Scale up to multiple nodes.
* Run a few more tests to ensure serialization of all messages sent over remoting works.

**Comment by sleipnir** [comment]
I would recommend start the minikube with more than one node as below and running the cluster tests:

```
minikube start --driver kvm2 --memory 8g --cpus 4 --nodes 3
```
