### ISSUE TITLE
Absence of the factory method for registering Action type entities

### ISSUE THREAD

**Issue by sleipnir** [cloudstateio/cloudstate#437]
The absence of a registration method that receives an ActionEntityFactory factory will make integration with spring support impossible. It would be interesting to fix this before launching new version of java-support and registering that restriction somewhere so that other programmers don't make the same mistake when creating a new type of entity.

**Comment by sleipnir** [comment]
ping @pvlugter

**Comment by pvlugter** [comment]
Okay. Not sure why the action registration methods are different, but should be no problem to add the equivalent factory approach as the entities. @jroper?

**Comment by pvlugter** [comment]
Action is different from the entities. While for entities, the factory is used to create an entity instance for each entity id, there's just one action instance for an action service. So if there's a factory, it would just be used to create the singleton action handler initially. Would a factory still then be needed for Spring support?

**Comment by sleipnir** [comment]
Yes it is necessary because I need to get the bean from the Spring context so that the dependency injection can work accordingly. I cannot let Cloudstate manage the life cycle for me as it has no way of injecting any type of addiction for me. 
The alternative would be a method that receives an instance of Object, instead of a Class<?>
But in this case the factory approach is more elegant

**Comment by jroper** [comment]
The method currently there receives `Object`, not `Class<?>`:

https://github.com/cloudstateio/cloudstate/blob/master/java-support/src/main/java/io/cloudstate/javasupport/CloudState.java#L252-L255

If we changed it to accept a factory, all that would happen is that method would immediately invoke the factory method to get a singleton instance that it would then use from then on.

**Comment by sleipnir** [comment]
Eu entendo a consequência da mudança e nao faz nenhuma diferença do ponto de vista do spring suporte. Só preciso que o objeto esteja no ciclo de vida do Spring primeiro. Os outros tipos cloudstate possuem uma fabrica e acho um bom arranjo isso, semanticamente faz mais sentido para mim, independente se internamente ele sera conduzido como um singleton ou prototype.  se vocês preferem um Object pra mim não faz diferença, eu nao notei que recebiam uma instância.
I understand the consequence of the change and it doesn't make any difference from the standpoint of spring support. I just need the object to be in the Spring lifecycle first. The other cloudstate types have a factory and I think this is a good arrangement, semantically it makes more sense to me, regardless if internally it will be conducted as a singleton or prototype. if you prefer an Object to me it makes no difference, I didn’t notice that you received an instance.

**Comment by sleipnir** [comment]
Thanks @jroper I will implement support for Actions in spring boot using the method that receives an object
