### ISSUE TITLE
Cloudstate protobuf files define an incorrect and incompatible "go_package"

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/cloudstate#455]
All Cloudstate `.protobuf` files define an incorrect and incompatible `go_package`:
https://github.com/cloudstateio/cloudstate/blob/v0.5.1/protocols/protocol/cloudstate/event_sourced.proto#L27
```
option go_package = "cloudstate/protocol";
```
While this works to some extent, some tools don't like the incorrect use of such a go package, one is [CUE](https://cuelang.org/docs/integrations/go/#download-cue-definitions-from-go-packages).
The protocol buffers [reference documentation](https://developers.google.com/protocol-buffers/docs/reference/go-generated#invocation) defines:
>The `.proto` file should contain a go_package option specifying the full import path of the Go package that contains the generated code.

which leads to the following correct definition:
```
option go_package = "github.com/cloudstateio/go-support/cloudstate/protocol;protocol";
```

The Go User Language Support Library with [milestone v0.2.x](https://github.com/cloudstateio/go-support/tree/feature/crdt_support/protobuf/protocol/cloudstate) corrects this. Changes have to be copied over to the main repository.

**Comment by pvlugter** [comment]
@marcellanz, sounds good to just go ahead and apply these changes to the cloudstate repo.
