### ISSUE TITLE
Javadoc search returns incorrect links

### ISSUE THREAD

**Issue by rstento** [cloudstateio/cloudstate#481]
I found this when searching on the javadoc for registerCrdtEntity. Even though it shows when I search, it returns a 404. You have to use this awkward url to actually find the page: https://cloudstate.io/docs/java/_attachments/api/io/cloudstate/javasupport/CloudState.html#registerCrdtEntity(java.lang.Class,com.google.protobuf.Descriptors.ServiceDescriptor,com.google.protobuf.Descriptors.FileDescriptor...) This caused links to break in the commercial doc. I've worked around by including the full link, if this gets fixed, pls let me know. It happens with a few others as well.

**Comment by pvlugter** [comment]
@rstento, I'm not sure what you're saying is broken. The link for `registerCrdtEntity` in the docs looks correct. Sure, it's an awkward link when it's a particular method with a long signature, but I'm not sure what you think needs to be fixed.

**Comment by pvlugter** [comment]
Okay, so this is just in the javadoc search. It returns links with an `undefined` before the package: `https://cloudstate.io/docs/java/_attachments/api/undefined/io/cloudstate/javasupport/...`.

**Comment by pvlugter** [comment]
Not sure why this would break links in the commercial docs though, what do you mean there? We'll look at why the javadoc search has the wrong links. Package links look fine, but classes are broken.

**Comment by pvlugter** [comment]
Had a quick look at this. The `undefined` in the javadoc search results is the module, since the docs are now built on Java 11. Have disabled this for now to fix the search result links in #482.
