### ISSUE TITLE
HTTP API default mappings

### ISSUE THREAD

**Issue by pvlugter** [cloudstateio/cloudstate#501]
The default mappings for the HTTP API are currently in the form `/v1/MethodName`, but method names can clash on multiple services. Noticed this when looking to include some tests for default mappings in the TCK proxy tests, but some of the different model services have the same method names.

Other solutions for HTTP/JSON transcoding, like Google Cloud Endpoints or grpc-gateway, use a default mapping of `/fully.qualified.ServiceName/MethodName`, such as `/com.example.shoppingcart.ShoppingCart/GetCart`, which is aligned with the fully qualified names used for gRPC calls. We should consider switching over to this for the default too.

**Comment by sleipnir** [comment]
I agre with proposal

**Comment by hepin1989** [comment]
That's what we do
