### ISSUE TITLE
How / when are new versions of cloudstate-proxy-dev-mode published

### ISSUE THREAD

**Issue by retgits** [cloudstateio/cloudstate#506]
I'm wondering how new versions of [`cloudstate-proxy-dev-mode`](https://hub.docker.com/r/cloudstateio/cloudstate-proxy-dev-mode/tags?page=1&ordering=last_updated) are built and pushed and when that happens. Does that only happen on new releases?

**Comment by marcellanz** [comment]
`cloudstate-proxy-dev-mode` is superfluous. It was replaced with `cloudstate-proxy-core` and config switching.
What dev-mode was can be run now with:
```
docker run ... cloudstate-proxy-core:latest -Dconfig.resource=dev-mode.conf
```

**Comment by retgits** [comment]
Okay, cool 😄 will those containers be tagged with releases as well? I saw only `latest` is available?

**Comment by marcellanz** [comment]
I think the travis build would:
https://github.com/cloudstateio/cloudstate/blob/master/.travis.yml#L76
https://github.com/cloudstateio/cloudstate/blob/master/build.sbt#L365

but the PR above mentioned was merged after the last release.

**Comment by retgits** [comment]
Awesome, that definitely answers my question

**Comment by marcellanz** [comment]
Cool :)
