### ISSUE TITLE
create Gitter channel

### ISSUE THREAD

**Issue by andyczerwonka** [cloudstateio/cloudstate#72]
I think it'd be useful to create a Gitter channel (or Discord,or whatever is convenient) for discussion, especially early on as the project is moving at a high pace.

**Comment by jroper** [comment]
Yeah I did look at creating a gitter room, but it wouldn't let me create one for this organisation (presumably there's already a cloudstateio?)

**Comment by andyczerwonka** [comment]
https://gitter.im/CloudState-IO/community
