### ISSUE TITLE
Create documentation describing how to add more language supports

### ISSUE THREAD

**Issue by viktorklang** [cloudstateio/cloudstate#74]
Make a straight forward how-to on how to add more language support.

**Comment by andyczerwonka** [comment]
Great Idea, I think this would really help the existing initiatives.

**Comment by viktorklang** [comment]
@andyczerwonka Here's an initial stab at documenting this, let's update as things progress!

https://github.com/cloudstateio/cloudstate/blob/master/docs/src/main/paradox/developer/language-support/index.md
