### ISSUE TITLE
Schedule a weekly contributors-confcall

### ISSUE THREAD

**Issue by viktorklang** [cloudstateio/cloudstate#77]
Current proposed time is 6am AEST Wednesday (this means Tuesday for US and Europe).

**Comment by akramtexas** [comment]
First, it took me a minute to disabuse myself of the notion that `AEST` does _not_ stand for `American` EST 😄 Second, and having done that, I found [a handy calculator online](http://www.timebie.com/std/aest.php) which tells me that your proposed time, @viktorklang, translates into (yes, `American` time, _this_ time) `3:00 PM (15:00) Tuesday` (Central Time) in Austin. Third, all good: That works for me, thanks 👍

**Comment by andyczerwonka** [comment]
I’m MST unfortunately, so 4am is a bit early. I could do 8am AEST, or is that too late for others.

**Comment by andyczerwonka** [comment]
Works for me.

**Comment by viktorklang** [comment]
Addressed by #94

**Comment by akramtexas** [comment]
@viktorklang I was looking for some meeting schedule-related details in PR #94 ...

**Comment by viktorklang** [comment]
@akramtexas https://github.com/cloudstateio/cloudstate/pull/94/files#diff-53bdbf8cc81e8976e90db161596eae1aR5 :)

**Comment by akramtexas** [comment]
@viktorklang 👍 😄
