### ISSUE TITLE
Make a handful of (minor) updates to README.md to enhance its flow and readability.

### ISSUE THREAD

**Issue by akramtexas** [cloudstateio/cloudstate#86]
- The CloudState `README.md` is just about the coolest guide that I've seen in a great long while; and I've pretty much seen them all. 
- The coherent narrative laid out in the `README.md` has done nothing less for me than give me a manifesto for building (and using) next generation serverless, the way it _should_ be done. Kudos 👍 
- It has, in short order, nicely framed `FaaS` in the context it should be seen; a first (important) step toward stateful cloud computing, but a first step nonetheless 🌩 
- With that, and with utmost respect for the design captured by the author(s) of this terrific `README.md`, I suggest that we make a handful of (minor) updates to it so as to enhance its flow and readability even more than it currently stands.

**Comment by akramtexas** [comment]
- All build checks on the related PR have passed. 
- At some point in time, will I get permissions to assign issues to myself? Thanks - In case the workflow we follow here is to have somebody assign issues to the relevant committer, I'm good with that workflow, too 👍

**Comment by viktorklang** [comment]
@akramtexas I think we need to set up a "committers" group or similar. Perhaps @jroper has some ideas?

**Comment by akramtexas** [comment]
@viktorklang Right, that sounds good. I'll defer to @jroper and you - Thanks, gentlemen 👍
